### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gabmars** [BigBrownBag/IMDB#1]
1. Топ каста собирается некорректно
2. Выходной файл имеет непонятную структуру, его невозможно прочитать без исходного кода создавшего его.
3. Обработка исключений перехватывает только один класс исключений и продолжает логику программы, что может вызвать повторную ошибку, которая уже ничем не перехватится.
4. Если судить по количеству строк "----------------" в выходном файле, то собирается намного меньше требуемого количества фильмов (~150-170). По другому количество записей в файле не знаю как посмотреть.

**Comment by BigBrownBag** [comment]
1. если топ каста = stars, то исправил
2. исправил в csv
3. исправил
4. возможно медленно грузит записи, либо по этим фильтрам менее 1000. добавил отображение количества прогруженных фильмов

**Comment by gabmars** [comment]
Принято
